baseurl = "https://libsora.so/"
languageCode = "ko-kr"
title = "/usr/lib/libsora.so"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  hostName = "libsora.so"
  googleAnalytics = "UA-37862172-2"
  disqusShortname = "libsora"
  twitterUsername = "if1live"

  socials = [
    ['Twitter', '//twitter.com/if1live'],
    ['GitHub', '//github.com/if1live'],
    ['BitBucket', '//bitbucket.org/if1live']
  ]

  links = []

  #=============
  # Twitter Card
  #=============
  # https://dev.twitter.com/cards
  # http://michaelmartinez.in/twitter-card-plugin-for-pelican.html
  twitterCardUse = true # (False)
  twitterCardSite = '@if1live'  # The site's Twitter handle like @my_blog
  twitterCardSiteId = ''  # The site's Twitter ID
  twitterCardCreator = ''  # Your twitter handle like @monkmartinez
  twitterCardCreatorId = ''  # The site creator's id
  gravatarUrl = 'https://www.gravatar.com/avatar/fb9672e7e0d256f39369595381d1ea07'
