language: go

go:
  - 1.9

sudo: false

env:
  global:
    - secure: "fP5qN5KZCnR5/mlwnIFpiaKKbm6Athe6G/EgGVRQJIVbVxrGpDCNSTsJIUIsBYsMFDahKrjZpnksx+yZ4eTrpccZI4Kg5WnuBd3W2je3poJoIULNlHc8f98lLvuKoqQK4sugowGwj0pyj2ughvHKgr6wHZ8wNAlKgl5u+sSh5bQ="

before_install:
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure
  - go get -u github.com/spf13/hugo
  - go get -u github.com/wellington/wellington/wt

script:
  - git clone --depth 1 --quiet https://${GH_TOKEN}@github.com/if1live/if1live.github.io.git output
  - bash ./bin/build_theme.sh
  - bash ./bin/deploy/publish_hugo.sh

after_success:
  - bash ./bin/deploy/push_output.sh

branches:
  only:
    - master

notifications:
  email: false
