language: python

python:
  - "2.7"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
    - content_cached

env:
  global:
    - secure: "m/oUuSPEErNy5L7aL4nL3eq0cJhCeBmODOdO9ChCWappu5SyhdxLbysYbIl5UP6D/DwldB5nU1Y27XrbZIx0xdjgwehClZLiCosKK8cq6N/wG9m5QeCNuZtm0n5r2WmEY68I2yWYNa8/UBRlEdeQ6bsFQHNYmCWjc67Cpa4zfLk="

before_install:
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH

install:
  - go get -u github.com/if1live/maya
  - go install github.com/if1live/maya
  - pip install -r pelican/requirements.txt -q
  - npm install -g less

script:
  - git clone --depth 1 --quiet https://${GH_TOKEN}@github.com/if1live/if1live.github.io.git output
  - ./bin/publish_pelican.sh

after_success:
  - ./bin/push_output.sh

branches:
  only:
    - master

notifications:
  email: false
