language: python

python:
  - "2.7"

env:
  global:
    - secure: "TSZFy8W4hmBc2yrmFOiLvmw/7o/C/eBB8nYpJo6zE8AYOKfTYFnus308IAdeEcnql0eetLG3QRWjtClT/hfY1E6k6IACqiH4KXkm+EOLEPb+jKItn8g9zJM3TS/rX5pmLbJmiai90sp1RFXK6LLuOQHDlmueC3s+KokXvaXeXl0="

before_install:
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"

install:
  - sudo apt-get install optipng libjpeg-turbo-progs
  - pip install -r requirements.txt
  - npm install -g less

script:
  - git clone --depth 5 --quiet https://${GH_TOKEN}@github.com/if1live/if1live.github.io.git output
  - make publish
  - cp CNAME output

after_success:
  - cd output
  - git add -f .
  - git commit -a -m "add new site content"
  - git push https://${GH_TOKEN}@github.com/if1live/if1live.github.io.git master --quiet

branches:
  only:
    - master

notifications:
  email: false

