language: go

go:
  - 1.11

sudo: false

# https://restic.net/blog/2018-09-02/travis-build-cache
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  global:
    - secure: "fP5qN5KZCnR5/mlwnIFpiaKKbm6Athe6G/EgGVRQJIVbVxrGpDCNSTsJIUIsBYsMFDahKrjZpnksx+yZ4eTrpccZI4Kg5WnuBd3W2je3poJoIULNlHc8f98lLvuKoqQK4sugowGwj0pyj2ughvHKgr6wHZ8wNAlKgl5u+sSh5bQ="

before_install:
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"
  - go get github.com/golang/dep/cmd/dep

install:
  - mkdir ${TRAVIS_HOME}/src
  - cd ${TRAVIS_HOME}/src
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go install --tags extended
  - cd ${TRAVIS_HOME}/gopath/src/github.com/if1live/libsora.so

  - go get github.com/wellington/wellington/wt
  - dep ensure

script:
  - rm -rf output
  - git clone --depth 1 --quiet https://${GH_TOKEN}@github.com/if1live/if1live.github.io.git output
  - bash ./bin/build_theme.sh
  - bash ./bin/deploy/publish_hugo.sh

after_success:
  - bash ./bin/deploy/push_output.sh

branches:
  only:
    - master

notifications:
  email: false
