language: python

python:
  - "2.7"
  
env:
  global:
    - secure: "kOmUz0WBkmQAW5EUp3rZBBbiKQ5dElFixmdJelnuMU4sgmDbMgx8RYf+3zuK9agT0wS8B7jd2K14o41w7ApMoxN8PS45sbYHH19YcBeiMblLnx+0rppOK1eMcXU4oypEA2RHQ/5F3KdJzE0IopxrF5vFbCID1Y5Xq30pgP8A8P0="


install:
  - pip install -r requirements.txt
  - npm install -g less
  
script:
  - make github_external
  