language: python

python:
  - "2.7"

env:
  global:
    - secure: "gsLRF2tCcZlJEeUazvSKWEN1v8NB7oSMR+jCDRKrnHIPdZHAc4LYcAQkzO7zmHNr6hXMVBlKCGezyxTedlmmW01qYOMdJk/U2+aLBuKjuP/i6NBY+dtEKABFHyDRYbeM6Cyv7aYcnquqob5tsLi4HX1y8KIyFa/WUMIkb8L1wZ4="

before_install:
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"

install:
  - sudo apt-get install optipng libjpeg-turbo-progs
  - pip install -r requirements.txt -q
  - npm install -g less

script:
  - git clone --depth 1 --quiet https://${GH_TOKEN}@github.com/if1live/if1live.github.io.git output
  - make publish
  - cp CNAME output

after_success:
  - cd output
  - git add -f .
  - git commit -a -m "add new site content"
  - git push https://${GH_TOKEN}@github.com/if1live/if1live.github.io.git master

branches:
  only:
    - master

notifications:
  email: false

