language: python

python:
  - "2.7"
  
env:
  global:
    - "TSZFy8W4hmBc2yrmFOiLvmw/7o/C/eBB8nYpJo6zE8AYOKfTYFnus308IAdeEcnql0eetLG3QRWjtClT/hfY1E6k6IACqiH4KXkm+EOLEPb+jKItn8g9zJM3TS/rX5pmLbJmiai90sp1RFXK6LLuOQHDlmueC3s+KokXvaXeXl0="


install:
  - pip install -r requirements.txt
  - npm install -g less
  
script:
  - make github_external
  