language: python

python:
  - "2.7"
  
env:
  global:
    - secure: "SIZXVDXBhRMYD+F2dSr81kJ1s8GQS7AOSW1XTxgGcUb/8zE497J2RcSJFXha0jNY0uG28wWP2GIzIefpd74OIbMXb98JXYNjeE3NfrsSQjyunIZz0As+mFNFAWy5W9GRYmNRxiMNit4EAzofsXQ7lHdrl9o4Ythz2pvEnPgv6zw="


install:
  - pip install -r requirements.txt
  - npm install -g less
  
script:
  - make github_external
  