language: python

python:
  - "2.7"
  
env:
  global:
    - secure: "nyxIsCLk2QwA6wAczjmjSQS0FyNvtjt/pTBCUq7aB6kH0f5dLkdwMlgWvo3QQSZg0+2WxFjLZNrqzaQx41os2bF/e+Np8YkxZVRiGQrw8TqO2vicAeYkIQYVmA/YRdzIhriur36K9kiTJKtYUJ3WTirqHegspxAOd31QWvibr9Y="


install:
  - pip install -r requirements.txt
  - npm install -g less
  
script:
  - echo $GH_TOKEN
  - make github_external
  