language: go

go:
  - 1.6.2

#sudo: false

env:
  global:
    - secure: "m/oUuSPEErNy5L7aL4nL3eq0cJhCeBmODOdO9ChCWappu5SyhdxLbysYbIl5UP6D/DwldB5nU1Y27XrbZIx0xdjgwehClZLiCosKK8cq6N/wG9m5QeCNuZtm0n5r2WmEY68I2yWYNa8/UBRlEdeQ6bsFQHNYmCWjc67Cpa4zfLk="

before_install:
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"

install:
  - sudo apt-get install ed
  - go get -u github.com/if1live/maya
  - go get -u github.com/spf13/hugo
  - go get -u github.com/wellington/wellington/wt

script:
  - git clone --depth 1 --quiet https://${GH_TOKEN}@github.com/if1live/if1live.github.io.git output
  - ./bin/build_theme_hugo.sh
  - ./bin/publish_hugo.sh

after_success:
  - ./bin/push_output.sh hugo

branches:
  only:
    - master

notifications:
  email: false
