language: python

python:
  - "2.7"
  
env:
  global:
    - secure: "Ut7tOawqbadTKd+yICcViKUrheqm5nq+naac4aE326j4K3kPzPt2GI6Z/7h1dPXB0awendrTRFyVG9aja0NZUsPCKkF5pQRJdf4CXQivYgcmvcmalmmhAqbGJnjPXql7bYcZ8QfqR+dCuLf8vxrcA1Q5eg2MtmwI/o0v4cnYs0M="


install:
  - pip install -r requirements.txt
  - npm install -g less
  
script:
  - echo $GH_TOKEN
  - make github_external
  