baseurl = "https://if1live.github.io/"
theme = "sora"
languageCode = "ko-kr"
title = "if1live space"

disqusShortname = "libsora"
googleAnalytics = "G-SKE54STL16"

hasCJKLanguage = true

Paginate = 10
PaginatePath = "page"

[permalinks]
posts = "/posts/:slug/"

[taxonomies]
tag = "tags"

[social]
twitter = 'if1live'

[params]
hostName = "if1live.github.io"
socials = [['GitHub', '//github.com/if1live']]
links = []
images = [
  'https://www.gravatar.com/avatar/fb9672e7e0d256f39369595381d1ea07?size=160',
]

[sitemap]
changefreq = "monthly"
priority = 0.5

[markup]
[markup.goldmark.renderer]
unsafe = true

[module]
[module.hugoVersion]
extended = true
min = "0.110.0"

[[module.mounts]]
excludeFiles = [
  "posts/**/maya/**",
  "posts/**/examples/**",
  "posts/**/node_modules/**",
  "posts/**/package.json",
  "posts/**/pnpm-lock.yaml",
]
source = "content"
target = "content"
