baseurl = "https://if1live.github.io/"
theme = "sora"
languageCode = "ko-kr"
title = "/usr/lib/libsora.so"

disqusShortname = "libsora"
googleAnalytics = "UA-37862172-2"

Paginate = 10
PaginatePath = "page"

[taxonomies]
  tag = "tags"

[params]
  hostName = "if1live.github.io"
  twitterUsername = "if1live"

  socials = [
    ['Twitter', '//twitter.com/if1live'],
    ['GitHub', '//github.com/if1live'],
    ['BitBucket', '//bitbucket.org/if1live']
  ]

  links = []

  #=============
  # Twitter Card
  #=============
  # https://dev.twitter.com/cards
  # http://michaelmartinez.in/twitter-card-plugin-for-pelican.html
  twitterCardUse = true # (False)
  twitterCardSite = '@if1live'  # The site's Twitter handle like @my_blog
  twitterCardSiteId = ''  # The site's Twitter ID
  twitterCardCreator = ''  # Your twitter handle like @monkmartinez
  twitterCardCreatorId = ''  # The site creator's id
  gravatarUrl = 'https://www.gravatar.com/avatar/fb9672e7e0d256f39369595381d1ea07'

[sitemap]
  changefreq = "monthly"
  priority = 0.5

[markup]
  [markup.highlight]
    # hugo 내장 markdown highlight 비활성화
    # 생성된 HTML은 가볍게 유지하고 js로 syntax highlight 다루고 싶다
    codeFences = false

  [markup.goldmark.renderer]
    unsafe = true

[module]
[module.hugoVersion]
extended = true
min = "0.110.0"

[[module.mounts]]
excludeFiles = [
  "posts/**/maya/**",
  "posts/**/examples/**",
]
source = "content"
target = "content"
