name = "sora"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/if1live/if1live.github.io"
tags = []
features = []
min_version = "0.110.0"

[author]
  name = "if1live"
  homepage = "https://github.com/if1live"

[original]
  name = "mini"
  homepage = "https://github.com/nodejh"
  repo = "https://github.com/nodejh/hugo-theme-mini"
